Repository prgrms-be-devcourse/NBE4-5-2-Team09, pull requests merged in 2025-03, with the labels that each got.

#21 Feat/8 user join
  backend/build.gradle
  backend/src/main/java/com/coing/domain/user/controller/UserController.java
  backend/src/main/java/com/coing/domain/user/controller/dto/UserLoginRequest.java
  backend/src/main/java/com/coing/domain/user/controller/dto/UserResponse.java
  backend/src/main/java/com/coing/domain/user/controller/dto/UserSignUpRequest.java
  backend/src/main/java/com/coing/domain/user/entity/Authority.java
  backend/src/main/java/com/coing/domain/user/entity/User.java
  backend/src/main/java/com/coing/domain/user/repository/UserRepository.java
  backend/src/main/java/com/coing/domain/user/service/AuthTokenService.java
  backend/src/main/java/com/coing/domain/user/service/UserService.java
  backend/src/main/java/com/coing/filter/JwtAuthenticationFilter.java
  backend/src/main/java/com/coing/global/config/SecurityConfig.java
  backend/src/main/java/com/coing/util/Ut.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/messages.properties
  backend/src/test/java/com/coing/CoingApplicationTests.java
  backend/src/test/java/com/coing/domain/user/controller/UserControllerTest.java
  backend/src/test/java/com/coing/domain/user/service/UserServiceTest.java
Labels: ✨ feature

#20 Feat/12 Setup Upbit WebSocket Connection
  .github/workflows/pull-request-ci.yml
  backend/build.gradle
  backend/src/main/java/com/coing/CoingApplication.java
  backend/src/main/java/com/coing/domain/coin/entity/Orderbook.java
  backend/src/main/java/com/coing/global/config/WebSocketClientConfig.java
  backend/src/main/java/com/coing/infra/upbit/adapter/UpbitDataService.java
  backend/src/main/java/com/coing/infra/upbit/adapter/UpbitWebSocketConnection.java
  backend/src/main/java/com/coing/infra/upbit/adapter/UpbitWebSocketService.java
  backend/src/main/java/com/coing/infra/upbit/dto/OrderbookDto.java
  backend/src/main/java/com/coing/infra/upbit/dto/UpbitWebSocketFormatDto.java
  backend/src/main/java/com/coing/infra/upbit/dto/UpbitWebSocketTicketDto.java
  backend/src/main/java/com/coing/infra/upbit/dto/UpbitWebSocketTypeDto.java
  backend/src/main/java/com/coing/infra/upbit/enums/EnumUpbitRequestType.java
  backend/src/main/java/com/coing/infra/upbit/enums/EnumUpbitWebSocketFormat.java
  backend/src/main/java/com/coing/infra/upbit/enums/EnumUpbitWebSocketType.java
  backend/src/main/java/com/coing/infra/upbit/handler/UpbitWebSocketHandler.java
  backend/src/main/java/com/coing/infra/upbit/handler/UpbitWebSocketOrderbookHandler.java
  backend/src/main/java/com/coing/standard/utils/UpbitUtils.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/application.yml
  backend/src/test/java/com/coing/domain/user/controller/UserControllerTest.java
  backend/src/test/java/com/coing/infra/upbit/UpbitConnectionIntegrationTest.java
  backend/src/test/java/com/coing/infra/upbit/adapter/UpbitWebSocketConnectionTest.java
  backend/src/test/java/com/coing/infra/upbit/adapter/UpbitWebSocketServiceTest.java
  backend/src/test/java/com/coing/infra/upbit/handler/UpbitWebSocketHandlerTest.java
  backend/src/test/java/com/coing/infra/upbit/handler/UpbitWebSocketOrderbookHandlerTest.java
  backend/src/test/java/com/coing/standard/utils/UpbitUtilsTest.java
Labels: ✨ feature, BE

#26 Fix/25: user bug fix
  backend/build.gradle
  backend/src/main/java/com/coing/CoingApplication.java
  backend/src/main/java/com/coing/domain/user/controller/UserController.java
  backend/src/main/java/com/coing/domain/user/entity/User.java
  backend/src/main/resources/messages.properties
  backend/src/test/java/com/coing/domain/user/controller/UserControllerTest.java
Labels: ❕HOTFIX

#23 Feat/9 add exception handling
  backend/src/main/java/com/coing/domain/user/service/AuthTokenService.java
  backend/src/main/java/com/coing/domain/user/service/UserService.java
  backend/src/main/java/com/coing/global/exception/BusinessException.java
  backend/src/main/java/com/coing/global/exception/RestExceptionHandler.java
  backend/src/main/java/com/coing/util/BasicResponse.java
  backend/src/main/resources/messages.properties
  backend/src/test/java/com/coing/domain/user/service/UserServiceTest.java
Labels: ✨ feature

#27 Feat/24 user signout
  backend/src/main/java/com/coing/domain/user/controller/UserController.java
  backend/src/main/java/com/coing/domain/user/service/AuthTokenService.java
  backend/src/main/java/com/coing/domain/user/service/UserService.java
  backend/src/main/resources/messages.properties
Labels: ✨ feature

#30 Feat/28 user exception
  backend/src/main/java/com/coing/domain/user/controller/UserController.java
  backend/src/main/java/com/coing/domain/user/controller/dto/UserLoginRequest.java
  backend/src/main/java/com/coing/domain/user/controller/dto/UserSignUpRequest.java
  backend/src/main/java/com/coing/domain/user/service/UserService.java
  backend/src/main/java/com/coing/global/config/MessageConfig.java
  backend/src/main/java/com/coing/global/exception/RestExceptionHandler.java
  backend/src/main/java/com/coing/util/MessageUtil.java
  backend/src/test/java/com/coing/domain/user/controller/UserControllerTest.java
  backend/src/test/java/com/coing/domain/user/service/UserServiceTest.java
Labels: ✨ feature, BE

#29 Feat/13 fetch coin orderbook
  .github/workflows/pull-request-reviewers.yml
  README.md
  backend/src/main/java/com/coing/domain/coin/entity/Orderbook.java
  backend/src/main/java/com/coing/domain/coin/orderbook/dto/OrderbookDto.java
  backend/src/main/java/com/coing/domain/coin/orderbook/entity/Orderbook.java
  backend/src/main/java/com/coing/domain/coin/orderbook/entity/OrderbookSnapshot.java
  backend/src/main/java/com/coing/domain/coin/orderbook/entity/OrderbookUnit.java
  backend/src/main/java/com/coing/domain/coin/orderbook/repository/OrderbookSnapshotRepository.java
  backend/src/main/java/com/coing/domain/coin/orderbook/service/OrderbookService.java
  backend/src/main/java/com/coing/global/config/SecurityConfig.java
  backend/src/main/java/com/coing/global/config/WebSocketConfig.java
  backend/src/main/java/com/coing/global/filter/JwtAuthenticationFilter.java
  backend/src/main/java/com/coing/infra/upbit/adapter/UpbitDataService.java
  backend/src/main/java/com/coing/infra/upbit/dto/UpbitWebSocketOrderbookDto.java
  backend/src/main/java/com/coing/infra/upbit/handler/UpbitWebSocketOrderbookHandler.java
  backend/src/main/java/com/coing/standard/utils/UpbitUtils.java
  backend/src/main/java/com/coing/util/Ut.java
  backend/src/test/java/com/coing/domain/coin/orderbook/entity/OrderbookTest.java
  backend/src/test/java/com/coing/domain/coin/orderbook/service/OrderbookServiceTest.java
  backend/src/test/java/com/coing/infra/upbit/handler/UpbitWebSocketOrderbookHandlerTest.java
  backend/src/test/java/com/coing/util/UtilTest.java
Labels: ✨ feature, BE

#45 Feat/11 ticker get
  backend/build.gradle
  backend/src/main/java/com/coing/domain/coin/ticker/dto/TickerDto.java
  backend/src/main/java/com/coing/domain/coin/ticker/entity/Ticker.java
  backend/src/main/java/com/coing/domain/coin/ticker/entity/enums/AskBid.java
  backend/src/main/java/com/coing/domain/coin/ticker/entity/enums/Change.java
  backend/src/main/java/com/coing/domain/coin/ticker/entity/enums/MarketState.java
  backend/src/main/java/com/coing/domain/coin/ticker/entity/enums/MarketWarning.java
  backend/src/main/java/com/coing/domain/coin/ticker/service/TickerService.java
  backend/src/main/java/com/coing/global/config/JacksonConfig.java
  backend/src/main/java/com/coing/infra/upbit/adapter/UpbitDataService.java
  backend/src/main/java/com/coing/infra/upbit/adapter/UpbitWebSocketService.java
  backend/src/main/java/com/coing/infra/upbit/dto/UpbitWebSocketTickerDto.java
  backend/src/main/java/com/coing/infra/upbit/handler/UpbitWebSocketTickerHandler.java
  backend/src/main/java/com/coing/util/LocalDateDeserializer.java
  backend/src/main/java/com/coing/util/LocalTimeDeserializer.java
  backend/src/test/java/com/coing/domain/coin/ticker/service/TickerServiceTest.java
  backend/src/test/java/com/coing/infra/upbit/adapter/UpbitWebSocketServiceTest.java
Labels: ✨ feature, BE

#44 Feat/10 fetch market list
  backend/src/main/java/com/coing/domain/coin/market/controller/MarketController.java
  backend/src/main/java/com/coing/domain/coin/market/controller/dto/MarketResponse.java
  backend/src/main/java/com/coing/domain/coin/market/dto/MarketDto.java
  backend/src/main/java/com/coing/domain/coin/market/entity/Market.java
  backend/src/main/java/com/coing/domain/coin/market/repository/MarketRepository.java
  backend/src/main/java/com/coing/domain/coin/market/service/MarketService.java
  backend/src/main/java/com/coing/global/config/RestTemplateConfig.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/coing/domain/coin/market/service/MarketServiceTest.java
Labels: ✨ feature, BE

#46 Feat/38 fetch coin trade
  backend/src/main/java/com/coing/domain/coin/common/enums/AskBid.java
  backend/src/main/java/com/coing/domain/coin/common/enums/Change.java
  backend/src/main/java/com/coing/domain/coin/ticker/dto/TickerDto.java
  backend/src/main/java/com/coing/domain/coin/ticker/entity/Ticker.java
  backend/src/main/java/com/coing/domain/coin/trade/dto/TradeDto.java
  backend/src/main/java/com/coing/domain/coin/trade/entity/Trade.java
  backend/src/main/java/com/coing/domain/coin/trade/service/TradeService.java
  backend/src/main/java/com/coing/infra/upbit/adapter/UpbitDataService.java
  backend/src/main/java/com/coing/infra/upbit/adapter/UpbitWebSocketService.java
  backend/src/main/java/com/coing/infra/upbit/dto/UpbitWebSocketTickerDto.java
  backend/src/main/java/com/coing/infra/upbit/dto/UpbitWebSocketTradeDto.java
  backend/src/main/java/com/coing/infra/upbit/handler/UpbitWebSocketTradeHandler.java
  backend/src/main/java/com/coing/util/LocalDateDeserializer.java
  backend/src/main/java/com/coing/util/LocalTimeDeserializer.java
  backend/src/test/java/com/coing/domain/coin/ticker/service/TickerServiceTest.java
  backend/src/test/java/com/coing/domain/coin/trade/service/TradeServiceTest.java
  backend/src/test/java/com/coing/infra/upbit/adapter/UpbitWebSocketServiceTest.java
Labels: ✨ feature, BE

#48 Feat/47 setting frontend
  backend/src/main/java/com/coing/global/config/SpringDocConfig.java
  backend/src/main/java/com/coing/global/init/DevInitData.java
  frontend/.gitignore
  frontend/README.md
  frontend/eslint.config.mjs
  frontend/next.config.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.mjs
  frontend/public/file.svg
  frontend/public/globe.svg
  frontend/public/next.svg
  frontend/public/vercel.svg
  frontend/public/window.svg
  frontend/src/app/favicon.ico
  frontend/src/app/globals.css
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
  frontend/tsconfig.json
Labels: ✨ feature, FE

#49 Feat/37 fetch coin by market
  backend/src/main/java/com/coing/domain/coin/market/controller/MarketController.java
  backend/src/main/java/com/coing/domain/coin/market/repository/MarketRepository.java
  backend/src/main/java/com/coing/domain/coin/market/service/MarketService.java
  backend/src/test/java/com/coing/domain/coin/market/service/MarketServiceTest.java
Labels: ✨ feature, BE

#51 Feat/47 add dev profile
  backend/src/main/java/com/coing/global/init/DevInitData.java
Labels: ✨ feature

#57 feat: setup next middleware
  README.md
  api_schema.json
  backend/src/main/java/com/coing/global/init/DevInitData.java
  frontend/.gitignore
  frontend/.nvmrc
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/user/login/page.tsx
  frontend/src/lib/api/client.ts
  frontend/src/lib/auth-helpers.ts
  frontend/src/middleware.ts
Labels: ✨ feature, FE

#54 Feat/32 user bookmark
  backend/src/main/java/com/coing/domain/bookmark/controller/BookmarkController.java
  backend/src/main/java/com/coing/domain/bookmark/controller/dto/BookmarkRequest.java
  backend/src/main/java/com/coing/domain/bookmark/controller/dto/BookmarkResponse.java
  backend/src/main/java/com/coing/domain/bookmark/controller/dto/BookmarkUpdateRequest.java
  backend/src/main/java/com/coing/domain/bookmark/entity/Bookmark.java
  backend/src/main/java/com/coing/domain/bookmark/repository/BookmarkRepository.java
  backend/src/main/java/com/coing/domain/bookmark/service/BookmarkService.java
  backend/src/main/java/com/coing/domain/user/CustomUserPrincipal.java
  backend/src/main/java/com/coing/domain/user/controller/UserController.java
  backend/src/main/java/com/coing/domain/user/repository/UserRepository.java
  backend/src/main/java/com/coing/domain/user/service/AuthTokenService.java
  backend/src/main/java/com/coing/global/filter/JwtAuthenticationFilter.java
  backend/src/main/resources/messages.properties
  backend/src/test/java/com/coing/domain/user/controller/UserControllerTest.java
Labels: ✨ feature, ♻️ refactor, BE

#58 feat: auth token in header
  api_schema.json
  backend/src/main/java/com/coing/domain/bookmark/controller/BookmarkController.java
  backend/src/main/java/com/coing/domain/user/controller/UserController.java
  backend/src/main/java/com/coing/domain/user/service/AuthTokenService.java
  backend/src/main/java/com/coing/domain/user/service/UserService.java
  backend/src/main/java/com/coing/util/Ut.java
Labels: ✨ feature, ♻️ refactor, BE

#60 Feat/52 show ticker
  .gitignore
  api_schema.json
  backend/src/main/java/com/coing/global/init/DevInitData.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/ClientPage.tsx
  frontend/src/app/components/CandleChart.tsx
  frontend/src/app/components/Header.tsx
  frontend/src/app/components/NewsList.tsx
  frontend/src/app/components/OrderBookList.tsx
  frontend/src/app/components/TradeList.tsx
  frontend/src/app/globals.css
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
  frontend/src/app/types/index.ts
  frontend/src/app/utils/mockData.ts
  frontend/tailwind.config.js
Labels: ✨ feature, FE

#61 feat: implement email verification process with JWT token (send link)
  backend/src/main/java/com/coing/domain/user/controller/UserController.java
  backend/src/main/java/com/coing/domain/user/email/service/EmailSenderService.java
  backend/src/main/java/com/coing/domain/user/email/service/EmailVerificationService.java
  backend/src/main/java/com/coing/domain/user/entity/User.java
  backend/src/main/java/com/coing/domain/user/service/UserService.java
  backend/src/main/java/com/coing/global/config/MailConfig.java
  backend/src/main/java/com/coing/util/Ut.java
  backend/src/main/resources/application-test.yml
  backend/src/main/resources/application.yml
  backend/src/main/resources/messages.properties
  backend/src/test/java/com/coing/domain/user/controller/UserControllerTest.java
  backend/src/test/java/com/coing/domain/user/service/UserServiceTest.java
Labels: ✨ feature, BE

#64 feat: update email verification process with configurable URL and dummy
  backend/src/main/java/com/coing/domain/user/email/service/EmailSenderService.java
  backend/src/main/resources/application-test.yml
  backend/src/main/resources/application.yml
  backend/src/main/resources/messages.properties
Labels: ♻️ refactor, BE

#68 Feat/62 show user domain
  backend/src/main/java/com/coing/domain/user/controller/UserController.java
  backend/src/main/java/com/coing/domain/user/controller/dto/EmailVerificationResponse.java
  backend/src/main/java/com/coing/domain/user/controller/dto/UserLogoutRequest.java
  backend/src/main/java/com/coing/global/config/SecurityConfig.java
  frontend/.idea/git_toolbox_prj.xml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/components/Header.tsx
  frontend/src/app/context/auth-context.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/user/email-verification/page.tsx
  frontend/src/app/user/login/page.tsx
  frontend/src/app/user/signup/page.tsx
  frontend/src/app/utils/parse-token.ts
  frontend/src/middleware.ts
Labels: ✨ feature, FE

#70 feat: move secret keys to doppler
  .gitignore
  backend/package.json
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/application.yml
  doppler.yaml
  frontend/.gitignore
  frontend/.idea/git_toolbox_prj.xml
  frontend/package-lock.json
  frontend/package.json
  package-lock.json
  package.json
  turbo.json
Labels: ♻️ refactor, BE

#73 Feat/65 update websocket
  frontend/src/app/coin/[market]/ClientPage.tsx
  frontend/src/app/coin/[market]/page.tsx
  frontend/src/app/context/WebSocketContext.tsx
  frontend/src/app/store/webSocketStore.ts
Labels: ✨ feature, FE

#77 Feat/75 show trade
  backend/src/main/java/com/coing/domain/coin/trade/service/TradeService.java
  backend/src/test/java/com/coing/domain/coin/trade/service/TradeServiceTest.java
  frontend/src/app/coin/[market]/ClientPage.tsx
  frontend/src/app/coin/[market]/page.tsx
  frontend/src/app/coin/components/TradeList.tsx
  frontend/src/app/context/WebSocketContext.tsx
  frontend/src/app/types/index.ts
  frontend/src/app/utils/mockData.ts
Labels: ✨ feature, FE

#76 Feat/69 candle refactor
  backend/build.gradle
  backend/src/main/java/com/coing/domain/coin/candle/controller/CandleController.java
  backend/src/main/java/com/coing/domain/coin/candle/dto/CandleChartDto.java
  backend/src/main/java/com/coing/domain/coin/candle/dto/CandleDto.java
  backend/src/main/java/com/coing/domain/coin/candle/entity/Candle.java
  backend/src/main/java/com/coing/domain/coin/candle/entity/CandleSnapshot.java
  backend/src/main/java/com/coing/domain/coin/candle/enums/CandleInterval.java
  backend/src/main/java/com/coing/domain/coin/candle/repository/CandleSnapshotRepository.java
  backend/src/main/java/com/coing/domain/coin/candle/service/CandleChartService.java
  backend/src/main/java/com/coing/domain/coin/candle/service/CandleSnapshotService.java
  backend/src/main/java/com/coing/domain/coin/candle/service/CandleWebSocketPushService.java
  backend/src/main/java/com/coing/domain/coin/candle/service/UpbitCandleService.java
  backend/src/main/java/com/coing/domain/user/controller/UserController.java
  backend/src/main/java/com/coing/domain/user/controller/dto/UserSignupResponse.java
  backend/src/main/java/com/coing/global/config/CacheConfig.java
  backend/src/main/java/com/coing/infra/upbit/adapter/UpbitWebSocketCandleService.java
  backend/src/main/java/com/coing/infra/upbit/dto/UpbitWebSocketCandleDto.java
  backend/src/main/java/com/coing/infra/upbit/handler/UpbitWebSocketCandleHandler.java
  backend/src/main/resources/application-dev.yml
  backend/src/test/java/com/coing/domain/candle/CandleChartServiceTest.java
  frontend/src/app/coin/[market]/ClientPage.tsx
  frontend/src/app/coin/components/CandleChart.tsx
  frontend/src/app/context/auth-context.tsx
  frontend/src/app/types/index.ts
  frontend/src/app/user/signup/page.tsx
  frontend/src/lib/api/client.ts
Labels: ✨ feature, ♻️ refactor, BE, FE

#78 Feat/14 setup secret key cloud
  .github/workflows/pull-request-ci.yml
  .nvmrc
  backend/package.json
  backend/src/main/resources/application.yml
  frontend/package.json
Labels: ⚒️ build

#82 Feat/35 coin websocket by market
  backend/build.gradle
  backend/src/main/java/com/coing/domain/coin/market/controller/MarketController.java
  backend/src/main/java/com/coing/domain/coin/market/service/MarketCacheService.java
  backend/src/main/java/com/coing/domain/coin/market/service/MarketService.java
  backend/src/main/java/com/coing/domain/coin/orderbook/dto/OrderbookDto.java
  backend/src/main/java/com/coing/domain/coin/orderbook/repository/OrderbookSnapshotRepository.java
  backend/src/main/java/com/coing/domain/coin/orderbook/service/OrderbookService.java
  backend/src/main/java/com/coing/domain/coin/ticker/dto/TickerDto.java
  backend/src/main/java/com/coing/domain/coin/ticker/entity/Ticker.java
  backend/src/main/java/com/coing/domain/coin/ticker/service/TickerService.java
  backend/src/main/java/com/coing/domain/coin/trade/service/TradeService.java
  backend/src/main/java/com/coing/global/config/CacheConfig.java
  backend/src/main/java/com/coing/infra/upbit/adapter/UpbitDataService.java
  backend/src/main/java/com/coing/infra/upbit/dto/UpbitWebSocketTickerDto.java
  backend/src/main/java/com/coing/infra/upbit/enums/EnumUpbitRequestType.java
  backend/src/main/java/com/coing/infra/upbit/handler/UpbitWebSocketOrderbookHandler.java
  backend/src/main/java/com/coing/infra/upbit/handler/UpbitWebSocketTickerHandler.java
  backend/src/main/java/com/coing/infra/upbit/handler/UpbitWebSocketTradeHandler.java
  backend/src/main/java/com/coing/infra/upbit/util/UpbitRequestBuilder.java
  backend/src/main/java/com/coing/util/PageUtil.java
  backend/src/main/java/com/coing/util/Ut.java
  backend/src/main/resources/application-dev.yml
  backend/src/test/java/com/coing/domain/coin/market/service/MarketServiceTest.java
  backend/src/test/java/com/coing/domain/coin/orderbook/service/OrderbookServiceTest.java
  backend/src/test/java/com/coing/domain/coin/ticker/service/TickerServiceTest.java
  backend/src/test/java/com/coing/domain/coin/trade/service/TradeServiceTest.java
  backend/src/test/java/com/coing/infra/upbit/handler/UpbitWebSocketOrderbookHandlerTest.java
  backend/src/test/java/com/coing/util/UtilTest.java
  frontend/package-lock.json
  package-lock.json
  package.json
Labels: ⛔️ bug, BE

#85 Feat/79 user refactor
  backend/src/main/java/com/coing/domain/user/controller/UserController.java
  backend/src/main/java/com/coing/domain/user/controller/dto/UserResponse.java
  backend/src/main/java/com/coing/domain/user/controller/dto/UserSignUpRequest.java
  backend/src/main/java/com/coing/domain/user/email/service/EmailVerificationService.java
  backend/src/main/java/com/coing/domain/user/entity/User.java
  backend/src/main/java/com/coing/domain/user/service/UserService.java
  backend/src/main/java/com/coing/global/config/SecurityConfig.java
  backend/src/main/java/com/coing/global/exception/BusinessException.java
  backend/src/main/java/com/coing/global/exception/RestExceptionHandler.java
  backend/src/main/java/com/coing/global/security/CustomAuthenticationEntryPoint.java
  backend/src/main/java/com/coing/global/security/filter/JwtAuthenticationFilter.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/messages.properties
  backend/src/test/java/com/coing/domain/user/service/UserServiceTest.java
  frontend/src/app/coin/[market]/ClientPage.tsx
  frontend/src/app/components/Header.tsx
  frontend/src/app/context/auth-context.tsx
  frontend/src/app/user/email-verification/page.tsx
  frontend/src/app/user/email/email-verification-result/page.tsx
  frontend/src/app/user/email/email-verification/page.tsx
  frontend/src/app/user/login/page.tsx
  frontend/src/app/user/signup/page.tsx
Labels: ✨ feature, ♻️ refactor, BE, FE

#86 Feat/35 market detail page for orderbook components
  backend/src/main/java/com/coing/domain/coin/common/dto/PagedResponse.java
  backend/src/main/java/com/coing/domain/coin/market/controller/MarketController.java
  backend/src/main/java/com/coing/domain/coin/market/controller/dto/MarketResponse.java
  backend/src/main/java/com/coing/domain/coin/market/service/MarketService.java
  frontend/package-lock.json
  frontend/package.json
  frontend/public/logo.svg
  frontend/src/app/api/market/route.ts
  frontend/src/app/api/markets/route.ts
  frontend/src/app/coin/[market]/ClientPage.tsx
  frontend/src/app/coin/[market]/page.tsx
  frontend/src/app/coin/components/CandleChart.tsx
  frontend/src/app/coin/components/NewsList.tsx
  frontend/src/app/coin/components/OrderbookList.tsx
  frontend/src/app/coin/components/TradeList.tsx
  frontend/src/app/coin/list/MarketList.tsx
  frontend/src/app/coin/list/page.tsx
  frontend/src/app/components/Header.tsx
  frontend/src/app/components/Pagination.tsx
  frontend/src/app/context/auth-context.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/user/login/page.tsx
  frontend/src/app/user/signup/page.tsx
  frontend/src/app/utils/parse-token.ts
  frontend/src/components/Header.tsx
  frontend/src/components/Pagination.tsx
  frontend/src/components/ui/label.tsx
  frontend/src/components/ui/skeleton.tsx
  frontend/src/components/ui/switch.tsx
  frontend/src/context/AuthContext.tsx
  frontend/src/context/WebSocketContext.tsx
  frontend/src/lib/api/client.ts
  frontend/src/lib/helpers/auth.helpers.ts
  frontend/src/lib/helpers/index.ts
  frontend/src/lib/utils.ts
  frontend/src/lib/utils/index.ts
  frontend/src/lib/utils/mock-data.util.ts
  frontend/src/lib/utils/parse-token.util.ts
  frontend/src/middleware.ts
  frontend/src/store/web-socket.store.ts
  frontend/src/types/index.ts
  package-lock.json
Labels: ✨ feature, FE

#91 Fix/89 fix trade
  backend/src/main/java/com/coing/infra/upbit/dto/UpbitWebSocketTradeDto.java
Labels: ⛔️ bug, BE

#92 feat: refactor authentication handling to use sessionStorage instead of cookies
  .nvmrc
  backend/src/main/java/com/coing/domain/user/controller/UserController.java
  backend/src/main/java/com/coing/domain/user/service/AuthTokenService.java
  frontend/src/app/user/login/page.tsx
  frontend/src/components/Header.tsx
  frontend/src/context/AuthContext.tsx
  frontend/src/middleware.ts
  package.json
Labels: ♻️ refactor, BE, FE

#94 feat: update authentication and bookmark handling, refactor user info retrieval
  backend/src/main/java/com/coing/domain/bookmark/controller/BookmarkController.java
  backend/src/main/java/com/coing/domain/bookmark/repository/BookmarkRepository.java
  backend/src/main/java/com/coing/domain/user/CustomUserPrincipal.java
  backend/src/main/java/com/coing/domain/user/controller/UserController.java
  backend/src/main/java/com/coing/domain/user/controller/dto/SignOutRequest.java
  backend/src/main/java/com/coing/domain/user/service/AuthTokenService.java
  backend/src/main/java/com/coing/domain/user/service/UserService.java
  backend/src/main/java/com/coing/global/security/filter/JwtAuthenticationFilter.java
  frontend/src/app/bookmark/ClientPage.tsx
  frontend/src/app/bookmark/page.tsx
  frontend/src/app/coin/list/MarketList.tsx
  frontend/src/app/coin/list/page.tsx
  frontend/src/app/user/info/page.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/NavLink.tsx
Labels: ✨ feature, ♻️ refactor, BE, FE

#105 feat: add cascade delete for user in bookmark entity
  backend/src/main/java/com/coing/domain/bookmark/entity/Bookmark.java
  frontend/package-lock.json
Labels: ⛔️ bug, BE

#110 Feat/109 husky lint precommit
  .husky/.gitignore
  .husky/pre-commit
  .huskyrc
  .lintstagedrc.json
  frontend/.prettierrc
  frontend/components.json
  frontend/eslint.config.mjs
  frontend/next.config.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.mjs
  frontend/src/app/ClientPage.tsx
  frontend/src/app/api/market/route.ts
  frontend/src/app/api/markets/route.ts
  frontend/src/app/bookmark/ClientPage.tsx
  frontend/src/app/bookmark/page.tsx
  frontend/src/app/coin/[market]/ClientPage.tsx
  frontend/src/app/coin/[market]/page.tsx
  frontend/src/app/coin/components/CandleChart.tsx
  frontend/src/app/coin/components/NewsList.tsx
  frontend/src/app/coin/components/OrderbookList.tsx
  frontend/src/app/coin/components/TradeList.tsx
  frontend/src/app/coin/list/MarketList.tsx
  frontend/src/app/coin/list/page.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
  frontend/src/app/user/email/email-verification-result/page.tsx
  frontend/src/app/user/email/email-verification/page.tsx
  frontend/src/app/user/info/page.tsx
  frontend/src/app/user/login/page.tsx
  frontend/src/app/user/signup/page.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/NavLink.tsx
  frontend/src/components/Pagination.tsx
  frontend/src/components/ui/button.tsx
  frontend/src/components/ui/card.tsx
  frontend/src/components/ui/label.tsx
  frontend/src/components/ui/select.tsx
  frontend/src/components/ui/skeleton.tsx
  frontend/src/components/ui/switch.tsx
  frontend/src/components/ui/tabs.tsx
  frontend/src/context/AuthContext.tsx
  frontend/src/context/WebSocketContext.tsx
  frontend/src/lib/api/client.ts
  frontend/src/lib/helpers/auth.helpers.ts
  frontend/src/lib/helpers/index.ts
  frontend/src/lib/utils/index.ts
  frontend/src/lib/utils/mock-data.util.ts
  frontend/src/lib/utils/parse-token.util.ts
  frontend/src/middleware.ts
  frontend/src/store/web-socket.store.ts
  frontend/src/types/index.ts
  frontend/tailwind.config.js
  frontend/tsconfig.json
  package-lock.json
  package.json
Labels: ⚒️ build, FE

#112 refactor: dashboard-ui-pagination
  .husky/pre-commit
  frontend/src/app/api/market/route.ts
  frontend/src/app/api/markets/route.ts
  frontend/src/app/bookmark/ClientPage.tsx
  frontend/src/app/bookmark/page.tsx
  frontend/src/app/coin/[market]/ClientPage.tsx
  frontend/src/app/coin/list/ClientPage.tsx
  frontend/src/app/coin/list/MarketList.tsx
  frontend/src/app/coin/list/page.tsx
  frontend/src/app/globals.css
  frontend/src/components/Pagination.tsx
  frontend/src/components/ui/pagination.tsx
  frontend/src/lib/api/client.ts
  frontend/src/lib/api/fetch.ts
  frontend/src/lib/api/index.ts
  frontend/src/lib/helpers/auth.helpers.ts
  frontend/src/lib/utils/cn.utils.ts
  frontend/src/lib/utils/index.ts
  frontend/src/types/index.ts
Labels: ♻️ refactor, FE

#113 feat: user mail async
  backend/src/main/java/com/coing/domain/user/email/service/EmailVerificationService.java
  backend/src/main/java/com/coing/global/config/AsyncConfig.java
  frontend/src/app/user/email/email-verification/page.tsx
Labels: ✨ feature, ⛔️ bug, BE, FE

#118 Feat/102 fe header component
  frontend/public/logo.svg
  frontend/src/app/ClientPage.tsx
  frontend/src/app/bookmark/ClientPage.tsx
  frontend/src/app/bookmark/page.tsx
  frontend/src/app/globals.css
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
  frontend/src/app/user/info/page.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/NavLink.tsx
  frontend/src/components/RequireAutenticated.tsx
  frontend/src/context/AuthContext.tsx
  frontend/src/store/user.store.ts
  package.json
Labels: ⛔️ bug, FE

#117 feat: user frontend fix and add user method
  backend/src/main/java/com/coing/domain/user/controller/UserController.java
  backend/src/main/java/com/coing/domain/user/controller/dto/PasswordResetConfirmRequest.java
  backend/src/main/java/com/coing/domain/user/controller/dto/PasswordResetRequest.java
  backend/src/main/java/com/coing/domain/user/email/service/EmailSenderService.java
  backend/src/main/java/com/coing/domain/user/email/service/PasswordResetService.java
  backend/src/main/java/com/coing/domain/user/entity/User.java
  backend/src/main/java/com/coing/domain/user/repository/UserRepository.java
  backend/src/main/java/com/coing/domain/user/service/UserService.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/messages.properties
  backend/src/test/java/com/coing/domain/user/service/UserServiceTest.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/coin/components/CandleChart.tsx
  frontend/src/app/user/info/page.tsx
  frontend/src/app/user/login/page.tsx
  frontend/src/app/user/password-reset/page.tsx
  frontend/src/app/user/password-reset/request/page.tsx
  frontend/src/app/user/signup/page.tsx
  frontend/src/components/Header.tsx
Labels: ⛔️ bug, FE

#123 Feat/119 setup themeprovider
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/bookmark/ClientPage.tsx
  frontend/src/app/coin/components/CandleChart.tsx
  frontend/src/app/coin/components/NewsList.tsx
  frontend/src/app/coin/components/Ticker.tsx
  frontend/src/app/coin/components/TradeList.tsx
  frontend/src/app/coin/components/orderbook/OrderbookChart.tsx
  frontend/src/app/coin/components/orderbook/OrderbookHeader.tsx
  frontend/src/app/coin/components/orderbook/OrderbookList.tsx
  frontend/src/app/coin/list/ClientPage.tsx
  frontend/src/app/coin/list/page.tsx
  frontend/src/app/globals.css
  frontend/src/app/layout.tsx
  frontend/src/app/user/email/email-verification-result/page.tsx
  frontend/src/app/user/email/email-verification/page.tsx
  frontend/src/app/user/login/page.tsx
  frontend/src/app/user/password-reset/page.tsx
  frontend/src/app/user/password-reset/request/page.tsx
  frontend/src/app/user/signup/page.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/Pagination.tsx
  frontend/src/components/RequireAutenticated.tsx
  frontend/src/components/ThemeToggle.tsx
  frontend/src/components/ui/button.tsx
  frontend/src/components/ui/card.tsx
  frontend/src/components/ui/input.tsx
  frontend/src/context/ThemeContext.tsx
Labels: 🎨 design, FE

#126 Feat/101 refactoring api router
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/api/candle/route.ts
  frontend/src/app/coin/[market]/ClientPage.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/user/info/page.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/ui/alert-dialog.tsx
  frontend/src/components/ui/button.tsx
  frontend/src/components/ui/sonner.tsx
  frontend/src/lib/api/fetch.ts
  frontend/src/types/index.ts
Labels: ⛔️ bug, 🎨 design, FE

#137 Feat/132 fix add bookmark
  backend/src/main/java/com/coing/domain/bookmark/controller/BookmarkController.java
  backend/src/main/java/com/coing/domain/bookmark/service/BookmarkService.java
  backend/src/main/java/com/coing/domain/coin/market/service/MarketService.java
  frontend/src/app/coin/components/MarketCard.tsx
  frontend/src/app/coin/list/page.tsx
Labels: ⛔️ bug, BE, FE

#138 Feat/131 fe ver1 1 qa fix
  backend/docker-compose.yaml
  frontend/src/components/Header.tsx
  frontend/src/components/ThemeToggle.tsx
  frontend/src/context/AuthContext.tsx
  frontend/src/context/ThemeContext.tsx
  frontend/src/store/user.store.ts
  frontend/tailwind.config.js
Labels: ⛔️ bug, FE

#142 docs: add wireframe pages svg file
  docs/wireframes/bookmark-dashboard.svg
  docs/wireframes/coin-dashboard.svg
  docs/wireframes/coin-detail.svg
  docs/wireframes/email-verification.svg
  docs/wireframes/login.svg
  docs/wireframes/signup.svg
Labels: 📋 docs

#166 docs: Update README.md
  README.md
Labels: 📋 docs

#167 docs: Update README.md
  README.md
Labels: 📋 docs

#168 Feat/144 social login
  backend/build.gradle
  backend/src/main/java/com/coing/domain/bookmark/controller/BookmarkController.java
  backend/src/main/java/com/coing/domain/bookmark/service/BookmarkService.java
  backend/src/main/java/com/coing/domain/coin/market/controller/MarketController.java
  backend/src/main/java/com/coing/domain/coin/market/service/MarketService.java
  backend/src/main/java/com/coing/domain/user/controller/UserController.java
  backend/src/main/java/com/coing/domain/user/controller/dto/UserResponse.java
  backend/src/main/java/com/coing/domain/user/dto/CustomOAuth2User.java
  backend/src/main/java/com/coing/domain/user/dto/CustomUserPrincipal.java
  backend/src/main/java/com/coing/domain/user/dto/OAuth2UserDto.java
  backend/src/main/java/com/coing/domain/user/entity/Provider.java
  backend/src/main/java/com/coing/domain/user/entity/User.java
  backend/src/main/java/com/coing/domain/user/service/AuthTokenService.java
  backend/src/main/java/com/coing/domain/user/service/OAuth2UserService.java
  backend/src/main/java/com/coing/domain/user/service/UserService.java
  backend/src/main/java/com/coing/global/config/SecurityConfig.java
  backend/src/main/java/com/coing/global/security/filter/JwtAuthenticationFilter.java
  backend/src/main/java/com/coing/global/security/handler/OAuth2LoginFailureHandler.java
  backend/src/main/java/com/coing/global/security/handler/OAuth2LoginSuccessHandler.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/application-test.yml
  backend/src/main/resources/application.yml
  backend/src/main/resources/messages.properties
  frontend/public/kakao_login_medium_wide.png
  frontend/src/app/user/login/page.tsx
  frontend/src/app/user/social-login/callback/page.tsx
  frontend/src/app/user/social-login/page.tsx
Labels: ✨ feature, BE, FE
